version: '3.8'

services:
  dockup:
    build: .
    env_file: .env
    volumes:
      - /var/lib/docker/volumes:/mnt:ro
      - ~/.ssh:/root/.ssh:ro
    restart: always
    tty: true
    command: ["sh", "-c", "while true; do python src/main.py; sleep 86400; done"]