name: Release

on:
  push:
    tags:
      - "v*" # Triggers the workflow on version tags like v1.0, v2.1, etc.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions/setup-rust@v1
        with:
          toolchain: stable

      - name: Build
        run: cargo build --release

      - name: Compress binary
        run: tar -czf dockup.tar.gz target/release/dockup

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: dockup.tar.gz
          asset_name: dockup.tar.gz
          asset_content_type: application/gzip
